# Generated by Django 3.2.9 on 2021-11-22 06:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CameraDetails',
            fields=[
                ('camera_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=200)),
                ('weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ColorCode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('color_code', models.IntegerField()),
                ('color_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('contact_name', models.CharField(max_length=50)),
                ('contact_created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('city_code', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('last_inbound_contact_date', models.DateField(blank=True)),
                ('last_outbound_contact_date', models.DateField(blank=True)),
                ('last_contact_channel', models.CharField(default='call', max_length=200)),
                ('type', models.CharField(default='Individual', max_length=200)),
                ('photographerLevel', models.CharField(default='Professional', max_length=200)),
                ('camera_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.cameradetails')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.IntegerField()),
                ('event_name', models.CharField(max_length=200)),
                ('event_type', models.CharField(max_length=200)),
                ('event_date', models.DateTimeField()),
                ('event_channel', models.CharField(max_length=200)),
                ('event_city', models.CharField(max_length=200)),
                ('event_country', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ItemMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=200)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('breadth', models.IntegerField()),
                ('length', models.IntegerField()),
                ('material', models.CharField(max_length=200)),
                ('total_available_qty', models.IntegerField()),
                ('color_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.colorcode')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOffered',
            fields=[
                ('po_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_category', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ResDis',
            fields=[
                ('resdis_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('contact_name', models.CharField(max_length=50)),
                ('city_code', models.CharField(max_length=200)),
                ('contact_phone', models.CharField(max_length=200)),
                ('last_Inbound_contact_date', models.DateField()),
                ('last_Outbound_contact_date', models.DateField()),
                ('last_contact_channel', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('po_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.productoffered')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.contacts')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.itemmaster')),
                ('resdis_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.resdis')),
            ],
        ),
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('lead_id', models.AutoField(primary_key=True, serialize=False)),
                ('lead_created_date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('lead_name', models.CharField(max_length=50)),
                ('lead_type', models.DateField(default='Individual')),
                ('lead_converted', models.BooleanField(default=False)),
                ('lead_source', models.CharField(max_length=50)),
                ('lead_owner', models.CharField(max_length=200)),
                ('resdis_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.resdis')),
            ],
        ),
        migrations.CreateModel(
            name='EventContact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.contacts')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.events')),
            ],
        ),
        migrations.AddField(
            model_name='contacts',
            name='lead_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.leads'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='resdis_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.resdis'),
        ),
    ]
