# Generated by Django 3.2.9 on 2021-11-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='lead_owner',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='leads',
            name='lead_source',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='leads',
            name='lead_type',
            field=models.CharField(default='Individual', max_length=50),
        ),
    ]
