# Generated by Django 3.2.9 on 2021-11-24 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_auto_20211124_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='resdis_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ingestion.resdis'),
        ),
    ]
