# Generated by Django 3.2.9 on 2021-11-25 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0003_alter_leads_resdis_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='city_code',
        ),
        migrations.AddField(
            model_name='contacts',
            name='city',
            field=models.CharField(default='unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='contacts',
            name='country',
            field=models.CharField(default='unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='contacts',
            name='country_code',
            field=models.CharField(default='unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='contacts',
            name='region',
            field=models.CharField(default='unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='contacts',
            name='state',
            field=models.CharField(default='unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phone',
            field=models.CharField(default='unknown', max_length=200),
        ),
    ]
