# Generated by Django 3.2.9 on 2021-12-04 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0005_auto_20211130_0415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='name',
        ),
    ]
