# Generated by Django 3.2.9 on 2022-01-22 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0006_remove_contacts_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='resdis_id',
        ),
        migrations.RemoveField(
            model_name='leads',
            name='resdis_id',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='resdis_id',
        ),
        migrations.AlterField(
            model_name='contacts',
            name='category',
            field=models.CharField(default='Unknown', help_text='Category of photographer(Wedding etc)', max_length=200),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='city',
            field=models.CharField(default='unknown', help_text='Name of the contact', max_length=200),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='company_name',
            field=models.CharField(default='Unknown', help_text='Company Name', max_length=200),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='contact_created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, help_text='Potential contact created date'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='contact_name',
            field=models.CharField(help_text='Name of the contact', max_length=50),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='country',
            field=models.CharField(default='unknown', help_text='Country name of the contact', max_length=200),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='country_code',
            field=models.CharField(default='unknown', help_text='Country code of the contact', max_length=200),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.EmailField(help_text='Contact email id', max_length=254),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='last_contact_channel',
            field=models.CharField(default='call', help_text='last contact channel', max_length=200),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='last_inbound_contact_date',
            field=models.DateField(blank=True, help_text='last Inbound Sales contact date'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='last_outbound_contact_date',
            field=models.DateField(blank=True, help_text='last Outbound Sales contact date'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phone',
            field=models.CharField(default='unknown', help_text='Phone number', max_length=200),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='photographerLevel',
            field=models.CharField(default='Professional', help_text='Photographer Level , Professional or Novice', max_length=200),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='region',
            field=models.CharField(default='unknown', help_text='Region of the contact(e.g South, North)', max_length=200),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='state',
            field=models.CharField(default='unknown', help_text='State of the contact(e.g chennai, delhi)', max_length=200),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='type',
            field=models.CharField(default='Individual', help_text='Contact type (Individual or Redistributor)', max_length=200),
        ),
        migrations.AlterField(
            model_name='leads',
            name='lead_converted',
            field=models.BooleanField(default=False, help_text='Whether the Lead has bought a product or not'),
        ),
        migrations.AlterField(
            model_name='leads',
            name='lead_created_date',
            field=models.DateField(blank=True, default=datetime.datetime.now, help_text='Lead Creation Date'),
        ),
        migrations.AlterField(
            model_name='leads',
            name='lead_id',
            field=models.AutoField(help_text='Lead Id which is autogenerated', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='leads',
            name='lead_name',
            field=models.CharField(help_text='Name of the lead', max_length=50),
        ),
        migrations.AlterField(
            model_name='leads',
            name='lead_owner',
            field=models.CharField(default='Unknown', help_text='Sales Agent Handling the Lead', max_length=200),
        ),
        migrations.AlterField(
            model_name='leads',
            name='lead_source',
            field=models.CharField(default='Unknown', help_text='Source where the lead is generated', max_length=50),
        ),
        migrations.AlterField(
            model_name='leads',
            name='lead_type',
            field=models.CharField(default='Individual', help_text='Type of Lead (Individual or Redistributor)', max_length=50),
        ),
        migrations.DeleteModel(
            name='ResDis',
        ),
    ]
