# Generated by Django 3.2.9 on 2022-01-23 10:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0007_auto_20220122_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='lead_id',
        ),
        migrations.AddField(
            model_name='contacts',
            name='potential_lead',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', help_text='Contact is potential lead or not , default value is No', max_length=300),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='contact_created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 23, 10, 59, 54, 246053, tzinfo=utc), help_text='Potential contact created date'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='last_inbound_contact_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 1, 23, 10, 59, 54, 246175, tzinfo=utc), help_text='last Inbound Sales contact date'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='last_outbound_contact_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 1, 23, 10, 59, 54, 246192, tzinfo=utc), help_text='last Outbound Sales contact date'),
        ),
        migrations.AlterField(
            model_name='leads',
            name='lead_created_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 1, 23, 10, 59, 54, 248835, tzinfo=utc), help_text='Lead Creation Date'),
        ),
    ]
