# Generated by Django 3.2.9 on 2022-02-10 05:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0010_auto_20220123_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('version_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('data_type', models.CharField(max_length=100)),
                ('date_from', models.DateField(default=datetime.datetime(2022, 2, 10, 5, 54, 15, 984552, tzinfo=utc))),
                ('date_to', models.DateField(default=datetime.datetime(2022, 2, 10, 5, 54, 15, 984600, tzinfo=utc))),
                ('data_file', models.FileField(upload_to='documents')),
            ],
        ),
        migrations.AlterField(
            model_name='contacts',
            name='contact_created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 10, 5, 54, 15, 599200, tzinfo=utc), help_text='Potential contact created date'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='last_inbound_contact_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 2, 10, 5, 54, 15, 599356, tzinfo=utc), help_text='last Inbound Sales contact date'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='last_outbound_contact_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 2, 10, 5, 54, 15, 599379, tzinfo=utc), help_text='last Outbound Sales contact date'),
        ),
        migrations.AlterField(
            model_name='leads',
            name='lead_created_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 2, 10, 5, 54, 15, 602743, tzinfo=utc), help_text='Lead Creation Date'),
        ),
    ]
