# Generated by Django 3.2.9 on 2022-10-16 01:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0013_auto_20221009_0929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='influencers',
            old_name='id',
            new_name='Id',
        ),
        migrations.RenameField(
            model_name='photographerleads',
            old_name='lead_id',
            new_name='Id',
        ),
        migrations.RenameField(
            model_name='servicerequests',
            old_name='RequestID',
            new_name='Id',
        ),
        migrations.RemoveField(
            model_name='socialmediaenquiries',
            name='id',
        ),
        migrations.AddField(
            model_name='socialmediaenquiries',
            name='Id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='influencers',
            name='Date',
            field=models.DateField(default=datetime.date.today, help_text='Date'),
        ),
        migrations.AlterField(
            model_name='influencers',
            name='Facebook',
            field=models.URLField(help_text='Facebook Link', max_length=500),
        ),
        migrations.AlterField(
            model_name='influencers',
            name='Instagram',
            field=models.CharField(help_text='Instagram Link', max_length=500),
        ),
        migrations.AlterField(
            model_name='influencers',
            name='LinkedIn',
            field=models.URLField(help_text='LinkedIn Link', max_length=500),
        ),
        migrations.AlterField(
            model_name='influencers',
            name='Snapchat',
            field=models.CharField(help_text='Snapchat Link', max_length=500),
        ),
        migrations.AlterField(
            model_name='influencers',
            name='Twitter',
            field=models.CharField(help_text='Twitter Link', max_length=500),
        ),
        migrations.AlterField(
            model_name='influencers',
            name='Website',
            field=models.URLField(help_text='Website Link', max_length=500),
        ),
        migrations.AlterField(
            model_name='influencers',
            name='Youtube',
            field=models.URLField(help_text='Youtube Link', max_length=500),
        ),
    ]
