from django.db import models
import datetime
from django.utils import timezone
class Leads(models.Model):
    lead_id = models.AutoField(primary_key=True, help_text="Lead Id which is autogenerated")
    lead_created_date=models.DateField(default=datetime.datetime.now(tz=timezone.utc), blank=True,help_text="Lead Creation Date")
    lead_name=models.CharField(max_length=50,help_text="Name of the lead")
    lead_type=models.CharField(max_length=50,default='Individual',help_text="Type of Lead (Individual or Redistributor)")
    lead_converted=models.BooleanField(default=False,help_text="Whether the Lead has bought a product or not")
    lead_source=models.CharField(max_length=50,default='Unknown',help_text="Source where the lead is generated")
    lead_owner=models.CharField(max_length=200,default='Unknown',help_text="Sales Agent Handling the Lead")

    def __str__(self):
        return self.lead_name