from django.db import models
import datetime
from django.utils import timezone
from .utils.MasterData import Platforms,City,Country
from django.utils.timezone import now
class PhotographerLeads(models.Model):
    objects=None
    Id = models.AutoField(primary_key=True, help_text="Lead Id which is autogenerated")
    lead_created_date=models.DateField(default=datetime.date.today,help_text="Lead Creation Date")
    Pro=models.BooleanField(default=True,help_text="Whether the photographer is a pro or not")
    Youtube=models.URLField(max_length=500,help_text="Youtube Link")
    Instagram=models.CharField(max_length=500,help_text="Instagram Link")
    Snapchat=models.CharField(max_length=500,help_text="Snapchat Link")
    Facebook=models.URLField(max_length=500,help_text="Facebook Link")
    Twitter=models.CharField(max_length=500,help_text="Twitter Link")
    LinkedIn=models.URLField(max_length=500,help_text="Linkedin Profile")
    Website=models.URLField(max_length=500,help_text="Website Link")
    SalesPerson=models.CharField(max_length=500,help_text="Sales Person Assigned")
    Name=models.CharField(max_length=500,help_text="Name of the Photographer")
    Phone=models.IntegerField(max_length=20,help_text="Contact Number Home")
    Phone1=models.IntegerField(max_length=20,help_text="Contact Number Office")
    Phone2=models.IntegerField(max_length=20,help_text="Contact Number Mobile")
    Email=models.EmailField(max_length=100,help_text="Primary Email ID")
    Email1=models.EmailField(max_length=100,help_text="Secondary Email ID")
    Email2=models.EmailField(max_length=100,help_text="Alternative Email ID")
    ProductOwned=models.CharField(max_length=500,help_text="Current Camera Owned by Photographer")
    City = models.CharField(
        max_length=100,
        choices=City.choices,
        default=City.Delhi,
        help_text="City"
    )
    Country = models.CharField(
        max_length=100,
        choices=Country.choices,
        default=Country.INDIA,
        help_text="Country"
    )
    GenreTags=models.CharField(max_length=100,help_text="Genre ( Wedding,Movie etc)")